# Generated by Django 3.0.5 on 2020-04-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_artikel', models.CharField(max_length=255)),
                ('sub_judul_art', models.CharField(max_length=255)),
                ('isi_artikel', models.TextField()),
                ('media_artikel', models.FileField(upload_to='')),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100)),
                ('profile_pic', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komen_artikel', models.CharField(max_length=255)),
                ('pub_komen', models.DateField(verbose_name='date published')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Artikel')),
                ('komentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_artikel', models.IntegerField(default=0)),
                ('pub_like', models.DateField(verbose_name='date published')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Artikel')),
                ('komentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Users')),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Users'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Kategori'),
        ),
    ]
