# Generated by Django 3.0.5 on 2020-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0004_auto_20200411_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='media_artikel',
            field=models.FileField(blank=True, default='artikel/circleblue.png', null=True, upload_to='medium/static/images'),
        ),
    ]
