# Generated by Django 3.0.5 on 2020-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0005_auto_20200411_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='media_artikel',
            field=models.FileField(blank=True, default='artikel/circleblue.png', null=True, upload_to=''),
        ),
    ]
