# Generated by Django 3.0.5 on 2020-04-11 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0007_auto_20200411_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='media_artikel',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
