# Generated by Django 3.0.5 on 2020-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0008_auto_20200411_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='media_artikel',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
